### ISSUE TITLE
Sidebar navigation for sentiment doesn't take me to valid page

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#1223]
## Step 3: Describe the issue in more detail:

x-reference: [AIW-4849](https://steel-ventures.atlassian.net/browse/AIW-4849)

1. Open docs.veritone.com
2. In sidebar, select
  - aiWARE Overview & Concepts
  - Cognitive technology
  - Capabilities
  - Sentiment Analysis

Expect: I should see the sentiment analysis page
Actual: Page does not update

The URL changed to https://docs.veritone.com/#/cognitive-technology/cognitive/text/sentiment/ but that page doesn't seem to exist

**Comment by lulujo** [comment]
Closing as this is covered in AIW-4849.
