### ISSUE TITLE
Search doesn't work after navigation

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#1224]
## Step 3: Describe the issue in more detail:

1. Go to docs.veritone.com (reload the page)
2. Type "sentiment" in the search bar - see results, yay!
3. Press ESC to get rid of the search results
3. Click aiWARE Overview & Concepts in the sidebar
4. Type "sentiment" in the search bar - no more results

It seems as though using the sidebar navigation breaks search and you have to reload the page again to get search working

**Comment by lulujo** [comment]
Moved to DOC-63.
