### ISSUE TITLE
doc site doesn't match the /master branch of veritone/docs

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#1225]
## Step 3: Describe the issue in more detail:

I'm told that we don't have to "deploy" the docs site, but I can see this in the master branch https://github.com/veritone/docs/blob/master/src/docs/cognitive-technology/cognitive/text/sentiment/README.md

```
Example 1: Simple Output
The simplest possible sentiment output involves reporting a single positive or negative sentiment value for 
the entire document. A positive analysis would be reported like this:
<example>
And a negative analysis would would be reported like this:
<example>
Example 2: Richer Output
```

But when I look at the docs site https://docs.veritone.com/#/developer/engines/cognitive/text/sentiment/ it shows this:

```
Example 1: Simple Output
The simplest possible sentiment output involves reporting a single positive sentiment value for 
the entire document. Such an analysis would be reported like this:
<example>
Example 2: Richer Output
```

is there something I have to do to get my PRs deployed to the docs.veritone.com site?

> Interesting to note that there are 2 different copies of the "same" page on the documentation site:
> * https://docs.veritone.com/#/developer/engines/cognitive/text/sentiment/
> * https://docs.veritone.com/#/cognitive-technology/cognitive/text/sentiment/
> They both appear to be the “same” page, but the first one doesn’t match what’s in the /master branch of the docs repo. The 2nd one does

**Comment by kevmurray** [comment]
This feels like the site was refactored to move the content from `#/developer/engines/`... to `#/cognitive-technology/`... but not all the page's links were updated.

When docs gets "deployed" does it wipe the directories first, then deploy a clean copy? Or does it just keep deploying over-top of the old system? I'd rather get 404's that will get reported and fixed than links to obsolete pages that look like real ones

**Comment by lulujo** [comment]
It looks like the duplicate pages are still there, but as far as I can tell the rest has been resolved. If not, please open a Jira ticket.

DOC-64 created for the duplicate pages.
