### ISSUE TITLE
Update job quickstart to use engineResults query

### ISSUE THREAD

**Issue by SteveShaffer** [veritone/docs#21]
## Step 1: Are you in the right place?

Yes

## Step 2: Check [x] the type of issue being reported:

- [x] Out-of-date content
  
## Step 3: Describe the issue in more detail:

In the [jobs quickstart doc](https://docs.veritone.com/#/apis/job-quickstart?id=retrieve-job-outputs) under "retrieve job status," the same graphql queries demonstrate looking up assets by type and parsing their contents for retrieving engine results.

This can be drastically simplified by leveraging the engineResults query instead.  Example:
```graphql
query {
  engineResults(tdoId: <tdoId>, engineId: <engineId>) {
    ...
  }
}
```

That should work for all engine categories too so you don't need to have different documentation for each different engine category.

**Comment by lulujo** [comment]
Moved to DOC-71.
