### ISSUE TITLE
Issue on page: engines/classes/

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#22]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://chat.veritone.com/).

## Step 2: Check [x] the type of issue being reported:

- [] Typo
- [] Missing content
- [] Incomplete content
- [x] Out-of-date content
- [] Other
  
## Step 3: Describe the issue in more detail:
This page should be merged into the updated Capabilities page: https://docs.veritone.com/#/engines/engine_standards/capability/

**Comment by SteveShaffer** [comment]
Addressed by engines section content overhaul.  New home: https://veritone-docs-next.now.sh/#/developer/engines/cognitive/
