### ISSUE TITLE
Document User and Application Tracking

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#229]
https://docs.google.com/document/d/1KBINfrq1VDFolRWH42rCQ7Wwhb2xeUHziZL5F9vUc7I/edit#heading=h.gd5h5rb9x88s

**Comment by kasthomas2** [comment]
The usage tracking info (internal only) comes down to this:
Use the custom header `x-veritone-user`: <UserID> to track API usage at user level.
Use the custom header `x-veritone-application`: <ApplicationID> to track usage at app level.

This info can go on a Confluence page or even be e-mailed to the people who need to know about it.

**Comment by kasthomas2** [comment]
NOTE: There is no need to use custom headers here. The userID and appID are already in the JWT token (which is easily decoded).

**Comment by kasthomas2** [comment]
The tokens info is now incorporated into https://github.com/veritone/docs/tree/master/src/docs/quickstart/jobs/README.md .

We decided the two custom header tracking fields are for internal use only and need not be in the public doc at this time.
