### ISSUE TITLE
Create a doc for "working with Jobs"

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#231]
Please use the references below. The goal is for any level of user to learn how to create jobs in aiWARE, with both types of API. References (please check the box after deprecating/archiving these docs):
- [ ] https://github.com/veritone/realtime/wiki/GraphQL:-Create-Job-DAG-in-V3-Format
- [ ] https://docs.google.com/document/d/1QJ2KpoYWQI_rc0tafeyBChhTwtBIhR_asCSvfzgspt4/edit
- [ ] https://docs.google.com/document/d/1Ktk7gk3_Ac-p1emj5SCBjXhS_kjWqM6AXzHDcBxtL8w/edit#heading=h.roz4dvau5h94

**Comment by kasthomas2** [comment]
This can be closed now.
