### ISSUE TITLE
Edge updating and troubleshooting cookbook

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#245]
- [ ] Incorporate the information from: https://docs.google.com/document/d/14hYQNgwE9tvmQn08UT9MX6KZpF9rYqSASU2G9GBEYYE/edit?ts=5e5ff714#heading=h.fsknkxopf1l4
- [ ] Add a deprecation msg to the doc

**Comment by kasthomas2** [comment]
The Google doc makes no sense to me. It's a random dump of disconnected/disjoint information. Lacks context. I literally do not know what it means or what to do with it. Numerous topics are addressed in one doc. They do not "cohere" together. 

I need to understand this task a lot better.
