### ISSUE TITLE
How to View Engine Logs

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#246]
- [ ] Port and edit the content from this doc: https://docs.google.com/document/d/1Ktk7gk3_Ac-p1emj5SCBjXhS_kjWqM6AXzHDcBxtL8w/edit#heading=h.roz4dvau5h94
- [ ] Add a deprecation msg at the top

**Comment by kasthomas2** [comment]
This is documented now at https://github.com/veritone/docs/blob/master/src/docs/overview/aiWARE-in-depth/edge/logs.md (pushed to production).
