### ISSUE TITLE
Single Engine DAGs

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#247]
- [ ] Port and edit the content from this doc: https://docs.google.com/document/d/1fYuzX018daZwEaHqFOEHa5_5MyUVm0-aZ7fqhLw6TlY/edit
- [ ] Add a deprecation msg at the top

**Comment by kasthomas2** [comment]
Preview link (for Single-Engine Jobs documentation):
https://docs-2u1of5k4l.vercel.app/#/overview/aiWARE-in-depth/single-engine-jobs

**Comment by kasthomas2** [comment]
Documented at https://github.com/veritone/docs/blob/master/src/docs/overview/aiWARE-in-depth/single-engine-jobs.md and pushed to production.
