### ISSUE TITLE
Developer Terms & Conditions on docs.veritone.com

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#248]
On docs.veritone.com, the Developer Terms & Conditions link is currently under "Build Engines".  Since those terms relate to all things developer (not just building engines), please move the link to the top level directory (as the last link after "aiWARE Glossary" would be fine).  Please keep the same URL since that URL is referenced in various agreements: https://docs.veritone.com/#/developer/terms-and-conditions.

**Comment by aMacDawg** [comment]
https://github.com/veritone/docs/pull/250

**Comment by lulujo** [comment]
Closing as obsolete.

https://docs.veritone.com/#/developer/terms-and-conditions has the T&C.
