### ISSUE TITLE
[6] Document aiWARE Anywhere Alpha

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#254]
We're prepping the release of aiWARE Anywhere internally for our developers. We have a website ready at https://aiware-anywhere-mgmt.ops.veritone.com/ for them to use to create an instance for themselves. This will create a `m5.large` instance in the us-east-1 region of AWS for developers to use. After creating an instance using the web interface, the developers will have to open a terminal to add the host to /etc/hosts.

1. Go to https://aiware-anywhere-mgmt.ops.veritone.com/
2. Enter name and click on Add Instance
3. Click on view and add local.veritone.com to hosts file 
4. Use aiWARE Anywhere 
5. Delete the instance when done using the web interface at https://aiware-anywhere-mgmt.ops.veritone.com/

The m5.large instance has 2 vCPUs and 8GB of memory. In addition, each instance is given to 100GB of hard drive space. 

The following components are installed on the instnace:

- Edge Controller
- PostgreSQL Database
- ElasticSearch
- Redis
- NSQ
- GraphQL
- CMS
- Frontend App
- Admin App

Known Bugs

- The partitions for tasks and jobs have a bad constraint for created_date_time. This can be dropped to allow the creation and running of jobs. 

DocumentationaiWARE Anywhere information such as the token for V3, cluster ID and other information can be found at https://docs.google.com/document/d/10TmlZG373Ef6ldoCAEBj18tLbHu_NzFkxp_KPn_ycio/edit#heading=h.qfe5r36upibe

**Comment by kasthomas2** [comment]
What is this?

**Comment by kfiry** [comment]
@kasthomas2 please see updated details here. The code is about ready in an "alpha" mode. Most of the DX aspects are still open for discussion. Please have an initial review and let's discuss in our next 1:1. Thanks.

**Comment by kfiry** [comment]
Closing for now. Will have a more detailed plan for aiWARE Anywhere docs
