### ISSUE TITLE
Document Edge Priorities in CreateJob

### ISSUE THREAD

**Issue by kfiry** [veritone/docs#262]
https://docs.google.com/presentation/d/1qRELhuWaOjiZ4PQPL4aFmJtL_WmaoslH4fs-WFeGAhU/edit#slide=id.g76d5e1a463_0_629

**Comment by kasthomas2** [comment]
Added a section to Job Processing page: 
https://docs-3vmq2eedx.vercel.app/#/overview/aiWARE-in-depth/job-processing?id=execution-preferences (preview)
