### ISSUE TITLE
Capability-specific tag format explanations are inconsistent

### ISSUE THREAD

**Issue by SteveShaffer** [veritone/docs#3]
In the sample VERI standard doc, the capability-specific explanations for tag conventions are inconsistent between ground truth, content moderation, and gender.

    // Optional for whole file
    // Tags associated with this output. Format { 'key': 'name', 'value': 'value' }
    // FOR GROUND TRUTH:  Set tag to be 'groundTruth': '<provider>'
    // For Moderation, Key must be: moderation:adult, moderation:violence, moderation:nsfw,
    //  moderation:nudity, moderation:fakeNews, moderation:pii
    // For gender: gender[value=male|female]

https://github.com/veritone/docs/blob/feature/veri-standard-by-ref/docs/engines/engine_standards/veri-standard-sample.js#L46

We should confirm what the proper formats are and use the same consistent language to define each.  As it stands, some of these are rather ambiguous, especially since it doesn't specify whether the notation suggests data like `{"moderation": "adult"}`, `{"key": "moderation", "value": "adult"}`, or `{"moderation:adult": true}`.

As a side note, we should also explain what `score` means (if anything) when included, as in the example.

**Comment by lulujo** [comment]
Closing as obsolete.
