### ISSUE TITLE
Make names of engine webhooks consistent or explicitly configurable

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#302]
## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [x] Missing content
- [ ] Incomplete content
- [ ] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:
When reading the [Engine documentation](https://docs.veritone.com/#/developer/edge/engines), I note that is says you need to provide a `/ready` webhook, but then then examples and the rest of the documentation refers to the `/readyz` webhook.

### Optionally, add the suggested correction text here:

Change all the webhook documentation and examples to read `/ready` and `/process` everywhere. This will provide consistency and to remove mental speed bumps of trying to figure out the customization issues at the same time you are just trying to get a feel for how everything works.
Follow up in the section about the environment variables to clarify that `/ready` and `/process` are just the conventions, and that you could use any endpoint names you want so long as the webhook environment variables contain the correct webhook addresses.

**Comment by lulujo** [comment]
Added to DOC-68.
