### ISSUE TITLE
Spurious backslashes in sample code

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#303]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://chat.veritone.com/).

## Step 2: Check [x] the type of issue being reported:

- [x] Typo
- [ ] Missing content
- [ ] Incomplete content
- [ ] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:

Unnecessary (incorrect?) backslashes in code. You have to escape underscores in text to prevent them from being interpreted as italic, but in backtics they are not necessary

### If applicable, paste the text in question here:

`ENV AIWARE\_ENV\_WHITE\_LIST AIWARE\_BUILD\_ID,AIWARE\_xyz`

### Optionally, add the suggested correction text here:

`ENV AIWARE_ENV_WHITE_LIST AIWARE_BUILD_ID,AIWARE_xyz`

**Comment by lulujo** [comment]
@kevmurray I'm not seeing this in the docs so I'm going to mark it closed. If you find a live example, please create a DOC ticket and we'll take care of this.

**Comment by kevmurray** [comment]
This is still an issue - created https://steel-ventures.atlassian.net/browse/DOC-78
