### ISSUE TITLE
[2] Move Automate Studio Help content to docs

### ISSUE THREAD

**Issue by aMacDawg** [veritone/docs#306]
Move relevant help content to the docs from https://help.veritone.com/en/collections/1832512-veritone-automate-studio
- [ ] Determine if any of the content should be migrated to Docs.veritone.com (and if so, migrate)
- [ ] Unpublish the Intercom article on Automate Studio help center (if lacking permissions, let @aMacDawg know when to unpublish).

Refresh the Automate docs section
- [ ] This section is not good as is anymore: https://docs.veritone.com/#/automate-studio/flow-examples/README
- [ ] Remove this section or replace it with real tutorials and troubleshooting
- [ ] Update the FAQ section: https://docs.veritone.com/#/automate-studio/faq

**Comment by kfiry** [comment]
@aMacDawg do we have the old help docs from Intercom available somewhere? Please send them to @kasthomas2 so he can determine how much he can use from it. Thanks.

**Comment by aMacDawg** [comment]
thanks @kfiry , here are the Automate pages in Intercom -- as previously discussed, they have been unpublished and are in "draft" mode, un-viewable to the public.

@kasthomas2 , here are the intercom pages-- let me know if you need an Intercom account:

 - [Automate Studio User Guide](https://app.intercom.com/a/apps/ixc2n84g/articles/articles/3193488/show)
 - [Automate Node Palette Guide](https://app.intercom.com/a/apps/ixc2n84g/articles/articles/3431848/show)
 - [Automate Studio FAQ](https://app.intercom.com/a/apps/ixc2n84g/articles/articles/3136419/show)

Of these three, only the _Automate aiWARE Node Palette_ guide has not already been incorporated in some form in the docs

**Comment by kasthomas2** [comment]
I can't reach those links.
They want credit card info to start a free trial -- nope.
Is these some other way to see this content?

**Comment by aMacDawg** [comment]
No worries @kasthomas2 , I created a new intercom seat for you. Go ahead and accept the email invite, finish setting up your intercom account, and then you should have access to all the articles linked above!
