### ISSUE TITLE
[1] "Engine Toolkit" in documentation points to nothing or deprecated projects

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#308]
Whilst trying to learn how to develop an engine, I'm finding that the "Engine Toolkit" links on the docs page either go nowhere (404) or to the veritone/engine-toolkit github repo

I think the 404's are cropping up because of problems searching - I'll research and write up another issue for that if I can reproduce.

However, every link I found for "Engine Toolkit" takes me to https://github.com/veritone/engine-toolkit/

This project appears to be the V2 engine toolkit, deprecated a year ago, and Quynh says it shouldn't be public and will cause infinite loops in the system if used. She is advocating deleting it entirely.

The information/links to the Engine Toolkit needs to be updated. From what I understand, the engine toolkit is now retrieved from a docker image, and it is no longer possible to link to it. What Quynh said was
> about downloading the engine toolkit
> we shouldn't have the documentation says that
> it needs to be from the Docker image veritone/aiware-engine-toolkit
> otherwise things will not running - tasks get looped forever and failed.

however, there is no such repo as veritone/aiware-engine-toolkit, so I don't really know what it should say.

Personally, I spent 3 days working with that repo before being told that it was deprecated a year ago. Specifically, the paragraph that got me in trouble was on page https://docs.veritone.com/#/developer/engines/tutorial/ and says:
> While the example that follows uses NodeJS, you should note that it's possible to use any programming language to create a cognitive engine, as long as the runtimes can be packaged into a Docker image. See https://github.com/veritone/engine-toolkit/tree/master/engine/examples for engine examples written in Python and Go.

I spent 3 days working on the Go sample at this link, but when I went to create a PR, Quynh told me that that repo wasn't public, no one could access it, and it should be deleted.

**Comment by kasthomas2** [comment]
This is now addressed.
