### ISSUE TITLE
[2] Weird URLs when you search the documentation

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#310]
When you search the documentation, you get strange section titles, and sometimes 404 errors when navigating.

Steps:
1. Search for "Engine Toolkit"
1. Scroll to "Veritone Engine Developers' Toolkit" results

Expected: Title is `Veritone Engine Developers' Toolkit`
Actual: Title is `The Veritone Engine Developer's Toolkit <!-- {docsify-ignore} -->`

Click on that result and you go to `https://docs.veritone.com/#/developer/engines/tutorial/?id=the-veritone-engine-developer39s-toolkit-lt-docsify-ignore-gt`, but it feels like it should be `https://docs.veritone.com/#/developer/engines/tutorial/?id=the-veritone-engine-developer39s-toolkit`

I have also gotten a number of 404's while trying to navigate after a search, but I cannot reproduce them at this time.

**Comment by kasthomas2** [comment]
Search is working as designed (FWIW). 

I was not able to see 404s.
