### ISSUE TITLE
404 on engine toolkit link

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#366]
## Step 1: Are you in the right place?

yes

## Step 2: Check [x] the type of issue being reported:

- [x] Typo
- [ ] Missing content
- [ ] Incomplete content
- [ ] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:

On the engines getting started page https://docs.veritone.com/#/developer/engines/getting-started/ , the "Engine Toolkit" link on #2 is 404 Not Found

### If applicable, paste the text in question here:

Follow the instructions in the [Engine Toolkit] section to setup your local development environment.

### Optionally, add the suggested correction text here:

Possibly, the page moved to here https://docs.veritone.com/#/developer/edge/engines when it was updated to V3?

**Comment by lulujo** [comment]
Moved to DOC-65
