### ISSUE TITLE
Prune old VDA-related content

### ISSUE THREAD

**Issue by kasthomas2** [veritone/docs#373]
Per Chad meeting of 11.18.2020, deep-sweep doc pages to make sure text & screenshots are updated for the various UI features we decided to hide or nix. 
--  "AI" link on main VDA palette is going away.
--  Data Schemas UI (wizard) is going away.
-- GraphQL schema pages get nuked (replaced with Playground/Apollo UI, which will be shoehorned into VDA).
-- Remove (comment out) tutorial videos that show the old VDA UI (so, engine tutorial vids).

**Comment by lulujo** [comment]
Closing as obsolete.
