### ISSUE TITLE
Use /ready consistently (sometimes it's /readyz)

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#389]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://veritonedev.slack.com).

## Step 2: Check [x] the type of issue being reported:

- [x] Typo(ish)
- [ ] Missing content
- [ ] Incomplete content
- [ ] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:

We use `/ready` and `/readyz` as the webhook name for engines in different pages.

### Optionally, add the suggested correction text here:

We should just use `/ready` everywhere so people not familiar with some of the other systems that use /readyz, /livez, etc (like me :-) )won't be confused by the 'z'.
We should also note that actual name can be customized by environment variables in the Dockerfile (where appropriate). I think we already do this.

**Comment by aMacDawg** [comment]
@kevmurray , maybe I'm missing something but I don't think `/readyz` is a typo -- this was the expected webhook implemented in Engine Toolkit. @quynhdang-vt and/or @kasthomas2 may be able to provide more detail as needed

**Comment by kevmurray** [comment]
> @kevmurray , maybe I'm missing something but I don't think `/readyz` is a typo -- this was the expected webhook implemented in Engine Toolkit. @quynhdang-vt and/or @kasthomas2 may be able to provide more detail as needed

/readyz isn't a typo (which is why I said it was "typo-ish") in that we meant to put it in the docs, but it's a convention that doesn't belong to us. Using "readyz" is a convention we borrowed from Kubernetes - Kubernetes uses "readyz" so it doesn't interfere with a "ready" endpoint that the user might already be using. However that concern doesn't apply to us, so the the "ready" endpoint of an engine should be "ready" and having "readyz" in the documentation just looks like a typo to anyone who doesn't know that adding 'z' to the end of a word is a Kubernetes convention

**Comment by lulujo** [comment]
Moved to DOC-68.
