### ISSUE TITLE
Remove reference to "legacy" engine mode

### ISSUE THREAD

**Issue by kevmurray** [veritone/docs#394]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://veritonedev.slack.com).

## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [ ] Missing content
- [ ] Incomplete content
- [x] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:

On the engine manifest page: https://docs.veritone.com/#/developer/engines/standards/engine-manifest/?id=fields
The documented values for engineMode include "legacy" which Al says isn't valid and can be removed. Apparently it was related to the iron engines.

### If applicable, paste the text in question here:

> The mode for executing your engine. Allowed values are "legacy", "batch", "chunk", "stream". If omitted, we will use "legacy".

### Optionally, add the suggested correction text here:

> The mode for executing your engine. Allowed values are "batch", "chunk", "stream".

**Comment by lulujo** [comment]
Moved to DOC-70.
