### ISSUE TITLE
Document what deployment failed means for users of AiWare.

### ISSUE THREAD

**Issue by gv-veri** [veritone/docs#526]
See related jira [item](https://steel-ventures.atlassian.net/browse/AIW-4683)

## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.

## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [X] Missing content
- [X] Incomplete content
- [ ] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:

(From this postmortem)[https://docs.google.com/document/d/1GYUMMG4M7TmlGsdYlU-IGw_1SWFiZNiasYlQF_kVrek/edit#]

After uploading an engine and attempting to deploy it: sometimes the user is presented with an error message of "Deployment failed". If you click through to the documentation, this message is mentioned as a state the deployment can get into but there is no description of what it means or what to do about it. 

This ticket is to track updating that documentation to assist developers in understanding what the state means.

**Comment by lulujo** [comment]
Moved to DOC-68.
