### ISSUE TITLE
Incorrect (out-of-date) link in documentation

### ISSUE THREAD

**Issue by gv-veri** [veritone/docs#533]
## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [ ] Missing content
- [ ] Incomplete content
- [x] Out-of-date content
- [ ] Other

## Step 3: Describe the issue in more detail:
![image](https://user-images.githubusercontent.com/74156455/107255391-18d96c80-69ed-11eb-9d88-dcce6b3c460d.png)

Per customer:
On Sun, Feb 7, 2021 at 7:23 AM Alberto Guisande <aguisande@decisionscience.bi> wrote:
Hi,
I noticed this URL in documentation, that is leading to a 404 error (the correct destination RL should be: https://docs.veritone.com/#/developer/applications/quick-start/step-2 )

**Comment by lulujo** [comment]
Closing as obsolete.
