### ISSUE TITLE
Issue on page: developer/engines/cognitive/speech/transcription/?id=engine-output

### ISSUE THREAD

**Issue by SteveShaffer** [veritone/docs#74]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://chat.veritone.com/).

## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [ ] Missing content
- [x] Incomplete content
- [ ] Out-of-date content
- [ ] Other
  
## Step 3: Describe the issue in more detail:

For transcription vtn-standard output, we should document how to report silence.  I need to confirm with search indexing team but I believe there's a special word `"!silence"` that can be used to indicate a gap in speech.

Long-term I think we want to be more explicit about this.

Instead of:
```
series: [{
  words: [{
    "word": "!silence"
  }]
}]
```
do:
```
series: [{
  object: {
    type: "sound"
    label: "silence"
  }]
}]
```
![image](https://media.giphy.com/media/91X2MlgF7dHsA/giphy.gif)

But in the meantime, it can be a good way to indicate the possibility that the person wasn't speaking during that time, especially in a lattice.

Of course you can always just add NO series item for that time; that works too.  Series items are allowed to be sparse.

**Comment by lulujo** [comment]
Moved to DOC-67.
