### ISSUE TITLE
Issue on page: applications/apis/

### ISSUE THREAD

**Issue by kevinsheart** [veritone/docs#77]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://chat.veritone.com/).

## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [ ] Missing content
- [ ] Incomplete content
- [ ] Out-of-date content
- [ ] Other

### Optionally, add the suggested correction text here:
"404 - Not found" -- FYI: Veritone Docs --> Applications --> Quickstart --> Step 3 link https://docs.veritone.com/#/applications/apis/ "404 - Not found"

**Comment by SteveShaffer** [comment]
The structure's been changed since this was filed and I think the click path you reported is no longer erroring out.

![image](https://user-images.githubusercontent.com/877953/57892150-cb69a480-77f2-11e9-9f5c-62699c16c57e.png)
