### ISSUE TITLE
Issue on page: developer/engines/quick-start/

### ISSUE THREAD

**Issue by kevinsheart** [veritone/docs#84]
## Step 1: Are you in the right place?

  * For typos, errors, omissions, etc. in the documentation, complete the questions below and submit.
  * For general technical questions, [join us on Slack](https://chat.veritone.com/).

## Step 2: Check [x] the type of issue being reported:

- [ ] Typo
- [ ] Missing content
- [ ] Incomplete content
- [ ] Out-of-date content
- [ ] Other

### Optionally, add the suggested correction text here:

Links give a 404 not found error.

**Comment by SteveShaffer** [comment]
Not sure how you got there @kevinsheart but I've added an alias in the linked PR so future folks will get redirected to the new engines quick start experience.  Thanks for the report.
